# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jiao/JHY/qt/big_assignment_for_digital_image_processing/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f0f0f0;\n"
"}\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #aaa;\n"
"    border-radius: 5px;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 5px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #4a90d9;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #357abd;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2a5f8f;\n"
"}\n"
"QComboBox {\n"
"    padding: 5px;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 3px;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_left = QtWidgets.QVBoxLayout()
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_left.addWidget(self.labelTitle)
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout_left.addWidget(self.labelInfo)
        self.gbFileSystem = QtWidgets.QGroupBox(self.centralwidget)
        self.gbFileSystem.setObjectName("gbFileSystem")
        self.verticalLayout_file = QtWidgets.QVBoxLayout(self.gbFileSystem)
        self.verticalLayout_file.setObjectName("verticalLayout_file")
        self.btn_openImage = QtWidgets.QPushButton(self.gbFileSystem)
        self.btn_openImage.setObjectName("btn_openImage")
        self.verticalLayout_file.addWidget(self.btn_openImage)
        self.btn_openGT = QtWidgets.QPushButton(self.gbFileSystem)
        self.btn_openGT.setObjectName("btn_openGT")
        self.verticalLayout_file.addWidget(self.btn_openGT)
        self.btn_saveResult = QtWidgets.QPushButton(self.gbFileSystem)
        self.btn_saveResult.setObjectName("btn_saveResult")
        self.verticalLayout_file.addWidget(self.btn_saveResult)
        self.btn_batchProcess = QtWidgets.QPushButton(self.gbFileSystem)
        self.btn_batchProcess.setObjectName("btn_batchProcess")
        self.verticalLayout_file.addWidget(self.btn_batchProcess)
        self.verticalLayout_left.addWidget(self.gbFileSystem)
        self.gbDehaze = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDehaze.setObjectName("gbDehaze")
        self.verticalLayout_dehaze = QtWidgets.QVBoxLayout(self.gbDehaze)
        self.verticalLayout_dehaze.setObjectName("verticalLayout_dehaze")
        self.comboDehaze = QtWidgets.QComboBox(self.gbDehaze)
        self.comboDehaze.setObjectName("comboDehaze")
        self.verticalLayout_dehaze.addWidget(self.comboDehaze)
        self.btnApplyDehaze = QtWidgets.QPushButton(self.gbDehaze)
        self.btnApplyDehaze.setObjectName("btnApplyDehaze")
        self.verticalLayout_dehaze.addWidget(self.btnApplyDehaze)
        self.verticalLayout_left.addWidget(self.gbDehaze)
        self.gbDerain = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDerain.setObjectName("gbDerain")
        self.verticalLayout_derain = QtWidgets.QVBoxLayout(self.gbDerain)
        self.verticalLayout_derain.setObjectName("verticalLayout_derain")
        self.comboDerain = QtWidgets.QComboBox(self.gbDerain)
        self.comboDerain.setObjectName("comboDerain")
        self.verticalLayout_derain.addWidget(self.comboDerain)
        self.btnApplyDerain = QtWidgets.QPushButton(self.gbDerain)
        self.btnApplyDerain.setObjectName("btnApplyDerain")
        self.verticalLayout_derain.addWidget(self.btnApplyDerain)
        self.verticalLayout_left.addWidget(self.gbDerain)
        self.gbMetrics = QtWidgets.QGroupBox(self.centralwidget)
        self.gbMetrics.setObjectName("gbMetrics")
        self.verticalLayout_metrics = QtWidgets.QVBoxLayout(self.gbMetrics)
        self.verticalLayout_metrics.setObjectName("verticalLayout_metrics")
        self.btnCalculateMetrics = QtWidgets.QPushButton(self.gbMetrics)
        self.btnCalculateMetrics.setObjectName("btnCalculateMetrics")
        self.verticalLayout_metrics.addWidget(self.btnCalculateMetrics)
        self.btnCompareAlgorithms = QtWidgets.QPushButton(self.gbMetrics)
        self.btnCompareAlgorithms.setObjectName("btnCompareAlgorithms")
        self.verticalLayout_metrics.addWidget(self.btnCompareAlgorithms)
        self.verticalLayout_left.addWidget(self.gbMetrics)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_left.addWidget(self.progressBar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_left.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_left)
        self.verticalLayout_right = QtWidgets.QVBoxLayout()
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.splitterImages = QtWidgets.QSplitter(self.centralwidget)
        self.splitterImages.setOrientation(QtCore.Qt.Horizontal)
        self.splitterImages.setObjectName("splitterImages")
        self.gbOriginal = QtWidgets.QGroupBox(self.splitterImages)
        self.gbOriginal.setObjectName("gbOriginal")
        self.verticalLayout_original = QtWidgets.QVBoxLayout(self.gbOriginal)
        self.verticalLayout_original.setObjectName("verticalLayout_original")
        self.lblOriginal = ImageLabel(self.gbOriginal)
        self.lblOriginal.setObjectName("lblOriginal")
        self.verticalLayout_original.addWidget(self.lblOriginal)
        self.gbResult = QtWidgets.QGroupBox(self.splitterImages)
        self.gbResult.setObjectName("gbResult")
        self.verticalLayout_result = QtWidgets.QVBoxLayout(self.gbResult)
        self.verticalLayout_result.setObjectName("verticalLayout_result")
        self.lblResult = ImageLabel(self.gbResult)
        self.lblResult.setObjectName("lblResult")
        self.verticalLayout_result.addWidget(self.lblResult)
        self.verticalLayout_right.addWidget(self.splitterImages)
        self.gbInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.gbInfo.setObjectName("gbInfo")
        self.verticalLayout_info = QtWidgets.QVBoxLayout(self.gbInfo)
        self.verticalLayout_info.setObjectName("verticalLayout_info")
        self.textInfo = QtWidgets.QTextEdit(self.gbInfo)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.textInfo.setFont(font)
        self.textInfo.setReadOnly(True)
        self.textInfo.setObjectName("textInfo")
        self.verticalLayout_info.addWidget(self.textInfo)
        self.verticalLayout_right.addWidget(self.gbInfo)
        self.horizontalLayout.addLayout(self.verticalLayout_right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像去雾去雨系统 - 数字图像处理大作业"))
        self.labelTitle.setText(_translate("MainWindow", "图像去雾去雨系统"))
        self.labelInfo.setText(_translate("MainWindow", "组名：zzZ\n"
"成员：李彦博 焦浩洋 范凯纬"))
        self.gbFileSystem.setTitle(_translate("MainWindow", "文件/系统"))
        self.btn_openImage.setText(_translate("MainWindow", "打开图像"))
        self.btn_openGT.setText(_translate("MainWindow", "打开参考图(GT)"))
        self.btn_saveResult.setText(_translate("MainWindow", "保存结果"))
        self.btn_batchProcess.setText(_translate("MainWindow", "批量处理"))
        self.gbDehaze.setTitle(_translate("MainWindow", "去雾算法"))
        self.btnApplyDehaze.setText(_translate("MainWindow", "执行去雾"))
        self.gbDerain.setTitle(_translate("MainWindow", "去雨算法"))
        self.btnApplyDerain.setText(_translate("MainWindow", "执行去雨"))
        self.gbMetrics.setTitle(_translate("MainWindow", "评价指标"))
        self.btnCalculateMetrics.setText(_translate("MainWindow", "计算指标"))
        self.btnCompareAlgorithms.setText(_translate("MainWindow", "算法对比"))
        self.gbOriginal.setTitle(_translate("MainWindow", "原图"))
        self.lblOriginal.setText(_translate("MainWindow", "请打开图像"))
        self.gbResult.setTitle(_translate("MainWindow", "结果图"))
        self.lblResult.setText(_translate("MainWindow", "处理后显示"))
        self.gbInfo.setTitle(_translate("MainWindow", "程序说明 / 评价指标输出"))
        self.textInfo.setPlainText(_translate("MainWindow", "欢迎使用图像去雾去雨系统！\n"
"\n"
"使用说明：\n"
"1. 点击「打开图像」加载有雾/有雨图像\n"
"2. 可选：点击「打开参考图(GT)」加载清晰参考图\n"
"3. 选择去雾或去雨算法，点击执行\n"
"4. 点击「计算指标」查看评价结果\n"
"5. 点击「算法对比」进行多算法对比分析\n"
"\n"
"实现的算法：\n"
"【去雾】直方图均衡化、CLAHE、自适应暗通道、伽马校正\n"
"【去雨】中值滤波、双边滤波、导向滤波、形态学、低秩分解、稀疏编码\n"
"\n"
"评价指标：PSNR、SSIM、MSE、MAE、RMSE、熵、对比度、平均梯度、锐度、色彩丰富度"))
from main import ImageLabel
